---
name: Various Checks
# yamllint disable-line rule:truthy
permissions:
  contents: read
on: [push, pull_request]

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    container:
      image: registry.opensuse.org/devel/openqa/containers/tumbleweed:client
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Validate yaml
        run: |-
          curl https://openqa.opensuse.org/schema/JobScenarios-01.yaml -O
          openqa-validate-yaml --schema-file JobScenarios-01.yaml scenario-definitions.yaml
